In [40]:
import numpy as np

In [41]:
data1 = dict(np.load('/storage_common/nobilm/ml-simplefold/fine_tune_with_clusters/finetune_simplefold100M_ANECAG_THEO_INZMA_INACTIVE_merged/postcontinue/denovo_fix_symmetry_test_theo_no_stoc/theo_samples/sample_0001_theo_4000_noh_global_clusters_004061_assigned_clusters.npz', allow_pickle=True))
for k,v in data1.items(): print(k, v.shape)


residue_keys (300,)
residue_indices (300,)
frame_indices (1,)
labels_assigned (1, 300)
labels_halo (1, 300)
cluster_counts (300,)
descriptor_order (5,)
used_offset (1,)


In [42]:
# File1: obs 0 in theo with reference

In [43]:
data1['labels_assigned']

array([[ 5,  3,  0,  0,  0,  0,  0,  1,  2,  0,  3,  0,  1,  1,  0,  4,
         1,  0,  0,  0,  1,  0,  1,  0,  0,  2,  1,  3,  0,  0,  2,  0,
         5,  0,  1,  2,  0,  0,  0,  0,  2,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  2,  0,  0,  0,  1,  0,  4,  0,  0,  0,
         3,  0,  0,  0,  0,  3,  0,  0,  0,  0,  3,  0,  0,  0,  2,  2,
         1,  1,  2,  3,  1,  2,  1,  1,  0,  2,  2,  0,  0,  0,  0,  0,
         3,  0,  2,  0,  2,  0,  0,  0,  0,  3,  1,  0,  0,  0,  0,  4,
         0,  1,  2,  0,  0,  0,  2,  1,  0,  4,  1,  0,  2,  3,  2,  0,
         0,  1,  0,  1,  0,  0,  3,  2,  1,  0,  0,  1,  0,  0,  4,  1,
        14, 17,  2, 12,  4,  4,  1,  6,  1,  0,  0, 16,  1,  3,  2,  0,
         1,  1,  3,  0,  0,  2,  0,  0,  2,  1,  0,  3,  1,  0,  0,  0,
         0,  1,  0,  1,  2,  1,  1,  1,  0,  2,  3,  4,  4,  0,  2,  1,
         0,  5,  0,  1,  5,  0,  0,  5,  6,  1,  2,  9,  2, 19, 15,  3,
        10,  3,  5,  3,  3,  9,  5,  0,  3,  2,  1,  0,  5,  1, 

In [ ]:
data = dict(
    np.load(
        '/storage_common/nobilm/backmapping_pots_model/datasets/ANECAG_THEO_INZMA_INACTIVE_merged/without_hs/split_per_simulation_type/theo_4000_noh_global_clusters.npz',
        allow_pickle=True
    )
)
for k,v in data.items(): print(k, v.shape)


trajectory (4000, 2338, 3)
residue_cluster_ids (4000, 300)
dihedrals (4000, 300, 5)
frame_state_ids (4000,)
frame_indices (4000,)
atom_resids (2338,)
atom_names (2338,)
atom_residue_index (2338,)
residue_keys (300,)
residue_cluster_counts (300,)
state_id ()
sample_id ()
dihedral_keys (5,)
dihedral_atom_indices (300, 5, 4)
dihedral_mask (300, 5)
res_idx (300,)
res_idx_and_glob_cluster_id_per_frame (4000, 300)
atom_idx_and_glob_cluster_id_per_frame (4000, 2338)


In [45]:
data['residue_cluster_ids'][61] # reference

array([ 3,  3,  0,  0,  0,  0,  0,  2,  0,  0,  3,  0,  1,  2,  0,  4,  1,
        0,  0,  0,  1,  0,  1,  1,  0,  2,  1,  3,  0,  0,  2,  0,  5,  7,
        2,  2,  0,  0,  0,  0,  2,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  2,  0,  0,  0,  1,  0,  4,  1,  0,  0,  3,  0,  0,  0,
        0,  1,  0,  0,  0,  0,  3,  0,  0,  0,  2,  2,  1,  2,  1,  3,  1,
        0,  5,  1,  0,  2,  0,  0,  0,  0,  2,  0,  3,  0,  1,  0,  2,  0,
        0,  0,  2,  3,  1,  6,  1,  0,  0,  2,  0,  0,  2,  0,  0,  0,  2,
        1,  0,  4,  1,  0,  1,  3,  2,  1,  0,  1,  0,  4,  0,  0,  5,  2,
        0,  0,  0,  0,  0,  0, 15,  2,  6,  8,  4, 15,  4,  3,  1,  6,  1,
        0,  0, 16,  1,  3,  1,  0,  1,  3,  3,  1,  0,  2,  0,  0,  1,  1,
        0,  3,  1,  0,  0,  3,  0,  1,  0,  1,  2,  1,  1,  0,  0,  1,  1,
        4,  0,  0,  2,  1,  0,  5,  0,  1,  4,  0,  0,  5,  6,  1,  0, 13,
        6, 14, 12,  2,  3,  3,  6,  3,  3,  4,  5,  0,  3,  1,  1,  1,  2,
        1,  5,  0,  0,  0

In [46]:
data1['labels_assigned'][0] # assigned to sampled

array([ 5,  3,  0,  0,  0,  0,  0,  1,  2,  0,  3,  0,  1,  1,  0,  4,  1,
        0,  0,  0,  1,  0,  1,  0,  0,  2,  1,  3,  0,  0,  2,  0,  5,  0,
        1,  2,  0,  0,  0,  0,  2,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  2,  0,  0,  0,  1,  0,  4,  0,  0,  0,  3,  0,  0,  0,
        0,  3,  0,  0,  0,  0,  3,  0,  0,  0,  2,  2,  1,  1,  2,  3,  1,
        2,  1,  1,  0,  2,  2,  0,  0,  0,  0,  0,  3,  0,  2,  0,  2,  0,
        0,  0,  0,  3,  1,  0,  0,  0,  0,  4,  0,  1,  2,  0,  0,  0,  2,
        1,  0,  4,  1,  0,  2,  3,  2,  0,  0,  1,  0,  1,  0,  0,  3,  2,
        1,  0,  0,  1,  0,  0,  4,  1, 14, 17,  2, 12,  4,  4,  1,  6,  1,
        0,  0, 16,  1,  3,  2,  0,  1,  1,  3,  0,  0,  2,  0,  0,  2,  1,
        0,  3,  1,  0,  0,  0,  0,  1,  0,  1,  2,  1,  1,  1,  0,  2,  3,
        4,  4,  0,  2,  1,  0,  5,  0,  1,  5,  0,  0,  5,  6,  1,  2,  9,
        2, 19, 15,  3, 10,  3,  5,  3,  3,  9,  5,  0,  3,  2,  1,  0,  5,
        1,  4,  0,  0,  0

In [47]:
sum(data1['labels_assigned'][0] != data['residue_cluster_ids'][61])

np.int64(80)

In [48]:
################################

In [49]:
denovo = dict(np.load('/storage_common/nobilm/ml-simplefold/fine_tune_with_clusters/finetune_simplefold100M_ANECAG_THEO_INZMA_INACTIVE_merged/postcontinue/denovo_fix_symmetry_test_theo_no_stoc_DENOVO/denovo_samples/following_label_0_assigned_clusters.npz', allow_pickle=True))
for k,v in denovo.items(): print(k, v.shape)


residue_keys (300,)
residue_indices (300,)
frame_indices (1,)
labels_assigned (1, 300)
labels_halo (1, 300)
cluster_counts (300,)
descriptor_order (5,)
used_offset (1,)


In [50]:
denovo['labels_assigned'][0] # assigned to denovo when using 
# RAW_NPZ_PATH='/storage_common/nobilm/backmapping_pots_model/datasets/ANECAG_THEO_INZMA_INACTIVE_merged/without_hs/split_per_simulation_type/theo_4000_noh_global_clusters.npz'


array([ 5,  3,  0,  0,  0,  0,  0,  1,  2,  0,  3,  0,  1,  1,  0,  4,  1,
        0,  0,  0,  1,  0,  1,  0,  0,  2,  1,  3,  0,  0,  2,  0,  5,  0,
        1,  2,  0,  0,  0,  0,  2,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  2,  0,  0,  0,  1,  0,  4,  0,  0,  0,  3,  0,  0,  0,
        0,  3,  0,  0,  0,  0,  3,  0,  0,  0,  2,  2,  1,  1,  2,  3,  1,
        2,  1,  1,  0,  2,  2,  0,  0,  0,  0,  0,  3,  0,  2,  0,  2,  0,
        0,  0,  0,  3,  1,  0,  0,  0,  0,  4,  0,  1,  2,  0,  0,  0,  2,
        1,  0,  4,  1,  0,  2,  3,  2,  0,  0,  1,  0,  1,  0,  0,  3,  2,
        1,  0,  0,  1,  0,  0,  4,  1, 14, 17,  2, 12,  4,  4,  1,  6,  1,
        0,  0, 16,  1,  3,  2,  0,  1,  1,  3,  0,  0,  2,  0,  0,  2,  1,
        0,  3,  1,  0,  0,  0,  0,  1,  0,  1,  2,  1,  1,  1,  0,  2,  3,
        4,  4,  0,  2,  1,  0,  5,  0,  1,  5,  0,  0,  5,  6,  1,  2,  9,
        2, 19, 15,  3, 10,  3,  5,  3,  3,  9,  5,  0,  3,  2,  1,  0,  5,
        1,  4,  0,  0,  0

In [51]:
sum(denovo['labels_assigned'][0] != data['residue_cluster_ids'][61]) # reference

np.int64(80)

In [52]:
all(denovo['labels_assigned'][0] == data1['labels_assigned'][0])

True

In [ ]:
###### 
# denovo when using 
# # RAW_NPZ_PATH='/storage_common/nobilm/backmapping_pots_model/datasets/ANECAG_THEO_INZMA_INACTIVE_merged/without_hs/split_per_simulation_type/theo_4000_noh_global_clusters.npz'


denovo2 = dict(np.load('/storage_common/nobilm/ml-simplefold/fine_tune_with_clusters/finetune_simplefold100M_ANECAG_THEO_INZMA_INACTIVE_merged/postcontinue/denovo_fix_symmetry_test_theo_no_stoc_DENOVOv2/denovo_samples/following_label_0_assigned_clusters.npz', allow_pickle=True))
# for k,v in denovo2.items(): print(k, v.shape)

sum(denovo2['labels_assigned'][0] != data['residue_cluster_ids'][61])

residue_keys (300,)
residue_indices (300,)
frame_indices (1,)
labels_assigned (1, 300)
labels_halo (1, 300)
cluster_counts (300,)
descriptor_order (5,)
used_offset (1,)


np.int64(80)

In [54]:
all(denovo2['labels_assigned'][0] == data1['labels_assigned'][0])

True